# Generated by Django 6.0.6 on 2026-07-04 11:35

from django.db import migrations

import django_veo_admin_api.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_veo_admin_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"ordering": ("-action_time",), "verbose_name": "log entry", "verbose_name_plural": "log entries"},
        ),
        migrations.AlterModelManagers(
            name="logentry",
            managers=[
                ("objects", django_veo_admin_api.models.LogEntryManager()),
            ],
        ),
    ]
